language: node_js
sudo: false
node_js: stable
addons: 
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin local
env:
  global:
  - secure: XjiT9Nszehl1j/evbFw/O/mtwxxgDasrz//Se4/lz24sCF2baZ24UdGy0Wy6TBxu75iucHV879sD8LcSMD/97+e+bVpPM/gnSltgBPZSy4dlAURHMtQ7cD4Kt+73RgFq5rOKgmmuopAdrbll7MSWT9+6RLxo1HXL4kGSJJpfNTg1/0n/zFtHxufgi92BakmnSjytfF6usPAk9J3fQ5YG9Rt2/6vlyBePdfhdMhYWoNuz57rBS8isqq9A2MJwhIfz/e8a85vPln3ZcORqX0FIkYHByL3iXWpYAMW+huUljjCucJpILDDuthcBjIIaEhQFEERHSxqYBQMtE3P4R2oz/fpORS4WFYBgZ4Fb7QzjqDHMkKgVpec9qdLIa2QiQXxeCp0f+GN74J4IfPMDSoOWEBrGPwiA3n0+qxFUhBp/ULWW3v0uPqdP+2noPHrpFxC/Ug++FDMj9a3Wpp10fGhFKAeVw2bY2zz/mxefTmKjyHXv9lGcAD+AUvMDcIN0DRKnzC3EjsrpAVq5WR9BBwDiBG4dmRUp8+oxLEYoT1PMx0CsiETJlPdE7tw+JqZZnMeytReZ6Uzt6M4C93BbV1RWlxLmOMgyGTRHOjWCNaLNqDXlkdoHcz0bf7BMkLqTqJKsJEK5mrcf/75FrC/HGaoMSbLWSeWGEXS9NN2FpHO2E/U=
  - secure: Jw+DNlbFK/r2RBOcuAXoDjMnY2okH6bdfCjp2UUUS6L+6RNAAhMMPNStgEbgMm1vHhCrc9Q6iHq/AVuWktCHVT+Nb1ZGpYpWPB0VgejKnUv5TPk1EIJvXuvcdtMRDUlJLXuY9OBcPFQI8+H+4eOL9l6PPPTZiWrpHr+BZNWR9gNaZY7Z3jPTDKZ+Fb++7VChQ/7+8dJzz7ioFA1D+MSI3BgXf4pUWFzp4uatSkUVeaQUnhfbaZSlyMN8BRgK4IWwORn2/A9t0YHhPsVINHT72uOeUc4oYUPEVSmc1RZgfzPgvSTNExNs0A6Uf0ReZm8p5n3WOMD8IcCFTZhjPQX/2kFRiE6OhJH8fxMxsCyyJyn7Lfcb6nA3PxO3r2nK1G32d0al7G2mUGsuuVKWfjH10UmyFr+PxGaV4GEsNUsvikfq2+gxvllxDnUEsjbKjtuo7qsx7N0k+kUtgUIn28E8THU6/xt5SjeaAB2ryAWgAWDDXqW+VvFoC/PASQaKAriAiAz8Hm/OKTH2Us/uBMGAkUgkYdEzIF/sqCwHvdDpcyy/w6fRsNoRboGgOgmaOxC9WAAkxcrYS/HGkr2BB0nV1xuFnqETwVlmT0JwVTZfgw+nkLbXjP7cQVk/28whzjd7RnXULQBsAgBxG6BJwEdN2zAUedSUtUpX1p+NI5xv6d8=
